### ISSUE TITLE
Evotuning and red fluorescent proteins

### ISSUE THREAD

**Issue by spark157** [churchlab/UniRep#11]
Does the data used for evotuning contain red fluorescent proteins? I'm thinking of sequences from the anthozoan class with mCherry as an example.

In the paper under 'Collecting fluorescent protein homologs with EBI JackHMMer', it seems the reds would be included in the starting sequences coming in from Interpro IPRO011584. However, I'm not sure if by the end of the process the reds (or homologs) would still be in the dataset or if they would have been filtered out. 

If you could let me know it would be most appreciated.

Scott

**Comment by surgebiswas** [comment]
Indeed, it does contain RFPs!
