### ISSUE TITLE
Running UniRep and EvoTuning on longer sequences

### ISSUE THREAD

**Issue by 000generic** [churchlab/UniRep#12]
UniRep and EvoTuning look really exciting - and I'd like to use them for a protein 1110 aa long. Is it realistic to use UniRep and EvoTuning for such a long protein?  If so, I was wondering if you could offer advice on an AWS configuration that might work well.  Are there changes I need to make in running things for such a long protein?  Happy to provide additional details if it would be helpful.

Thank you,
Eric

**Comment by mengqvist** [comment]
I have the same question. In your tutorial file you mention that updates get "unwieldy" for longer sequences.

**Comment by surgebiswas** [comment]
Unfortunately it's not at this time. You could consider generating subsequences of your protein and averaging reps over these subsequences. More involved would be to implement a truncated backprop over time algorithm that only sends gradients back a certain number of steps into the sequence. We definitely welcome PRs along these lines! We may consider adding the latter at some point.
