### ISSUE TITLE
Example code to load evotuned model checkpoint

### ISSUE THREAD

**Issue by cclough** [churchlab/UniRep#15]
Would you mind adding an example of loading the evotuned model checkpoint? 

There seems to be a number of ways to save & load checkpoints across different tensorflow versions - i've tried several without luck

**Comment by surgebiswas** [comment]
It should load like the checkpoints as illustrated in the tutorial. Could you be more specific? We don't guarantee support across other TF versions (haven't tried) but welcome PRs on this matter!
