### ISSUE TITLE
CUDA 10.2 and TF-gpu 2.1 support

### ISSUE THREAD

**Issue by ptynecki** [churchlab/UniRep#19]
Good morning,

I'm wondering if the UniRep dev core team has a plan to upgrade the code base and support the newest CUDA, cuDNN and Tensorflow-GPU environment?

Thank you for your reply.

**Comment by Umbriona** [comment]
You could try the conversion tool that tensorflow provides to upgrade projects from TF1 to TF2.

**Comment by surgebiswas** [comment]
Sorry for the slow response, but we are not developing further on this repository. I'd refer you to a JAX re-implementation that others in the community are maintaining: https://github.com/ElArkk/jax-unirep. Of course this isn't in Tensorflow, but it's more up to date and likely compatible with newest CUDA/cuDNN.
