### ISSUE TITLE
Can this model used to represent a sequence of amino acids, not an entire protein sequence?

### ISSUE THREAD

**Issue by yangning116** [churchlab/UniRep#25]
Can this model used to represent a sequence of amino acids, not an entire protein sequence?
Like a 7nt-amino acid sequence

**Comment by surgebiswas** [comment]
Computationally, it shouldn't be a problem at all!

Surge Biswas

**Comment by surgebiswas** [comment]
Closing issue, but please re-open if you have more questions.
