### ISSUE TITLE
potential issue for run_gpu_docker.sh

### ISSUE THREAD

**Issue by beef-broccoli** [churchlab/UniRep#7]
Hello,

Just a small issue I discovered. In run_gpu_docker.sh:

`nvidia-docker run -it -p 8888:8888 -p 6006:6006 -v `pwd`:/notebooks  unirep-gpu:latest`

nvidia-docker is deprecated with the release of Docker 19.03. If docker is installed on local machine, this needs to be changed to:

`docker run --gpus all -it -p 8888:8888 -p 6006:6006 -v `pwd`:/notebooks  unirep-gpu:latest`

**Comment by sandias42** [comment]
Hi beef-broccoli,

Thanks for bringing this to our attention! I will update the docs to warn users about this api update. 

Best wishes,
Ethan
