### ISSUE TITLE
Re-implementation in JAX

### ISSUE THREAD

**Issue by ericmjl** [churchlab/UniRep#8]
Hi everybody,

I'm interested in collaborating on a re-implementation of the model in numpy/JAX, partially for self-education reasons, partially to get the model compatible with the rest of the PyData stack. TF is notoriously difficult to interop with other Python ecosystem tools, while JAX plays nicely with it's explicit replication of the NumPy API. 

Already got something started (though extremely partial), with the source code [here](https://github.com/ericmjl/fundl/blob/master/fundl/layers/rnn.py#L95). You can safely ignore the rest of the framework (it's a pedagogical one, not a production one), but the key idea is to re-implement the forward model step in such a way that we can then trivially parallelize at least the forward encoder step across multiple new protein sequences easily.

Are you all in the LMA area, btw? I work in Cambridge, but am happy to bike over (or host you at my work place) and hack on this, while also hopefully receiving an education from you all on how the model works at the level of the source code.

Cheers,
Eric

**Comment by surgebiswas** [comment]
Closing out this old issue, but referencing anyone reading to here: https://github.com/ElArkk/jax-unirep
